apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelsabr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pelsabr
  template:
    metadata:
      labels:
        app: pelsabr
    spec:
      containers:
      - name: pelsabr
        image: registry.public.linode.knows.technology:5000/pelsabr-amd64
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command: ["touch", "/run/secrets/edgeauth.key"]
        ports:
        - containerPort: 12909
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
      imagePullSecrets:
      - name: regcred

